name: Validate users.json with JSON Schema

on:
  pull_request:
    paths:
      - 'users.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install ajv

      - name: Run validation script
        run: node .github/scripts/validate-users-json.js
